### ISSUE TITLE
TypeError: Cannot set properties of null (setting 'genshin_uid')

### ISSUE THREAD

**Issue by Tomoeri-L** [koishijs/koishi-plugin-genshin#9]
` command executing command: genshin 105550141
    TypeError: Cannot set properties of null (setting 'genshin_uid')
        at _Command.<anonymous> (/root/koishi/node_modules/koishi-plugin-genshin/src/index.js:62:30)
        at _Command.execute (/root/koishi/node_modules/koishi-core/lib/index.js:840:38)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async _Session.execute (/root/koishi/node_modules/koishi-core/lib/index.js:1246:20)
        at async next (/root/koishi/node_modules/koishi-core/lib/index.js:2206:16)
        at async next (/root/koishi/node_modules/koishi-core/lib/index.js:2206:16)
        at async _App._handleMessage (/root/koishi/node_modules/koishi-core/lib/index.js:2219:5)
        at async Promise.all (index 0)
        at async _App.parallel (/root/koishi/node_modules/koishi-core/lib/index.js:1532: +6s
`

查询正常国服UID时，后台便会报错 有关的查询功能都没法使用，请问有解决办法吗

**Comment by dragon-fish** [comment]
1. koishi 版本？
2. plugin 版本？
3. 有配置数据库吗？是什么数据库？

**Comment by Tomoeri-L** [comment]
> 1. 锦鲤？ 2.插件？ 3.有配置数据库吗？是什么数据库？

1."koishi": "^3.14.2"
2."koishi-plugin-genshin": "^2.0.0-beta.15"
3.无数据库

**Comment by dragon-fish** [comment]
版本 15 需要配置任意数据库才能使用

另，版本 16 仅支持 mongodb

**Comment by Tomoeri-L** [comment]
> 版本 15 需要配置任意数据库才能使用
> 
> 另，版本 16 仅支持 mongodb

好的，感谢

**Comment by dragon-fish** [comment]
~~广告：插件的更新日志均发布在 koishi 官方 discord 服务器，建议加入 dc 获取最新的资讯~~
